### ISSUE TITLE
Less variables not accessible across files in dev

### ISSUE THREAD

**Issue by stevenvachon** [stealjs/steal#255]
main.less:

``` css
@test: blue;
```

page-super.less:

``` css
button { color:@test }
```

results in:

```
variable @test is undefined
```

---

The same occurs with [Myth](http://myth.io)/[steal-myth](https://github.com/stevenvachon/steal-myth) and its standardized variables.

main.less:

``` css
:root { --test:blue }
```

page-super.less:

``` css
button { color:var(--test) }
```
